apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipeline.openshift.io/started-by: dan.ebenal@gov.bc.ca
    results.tekton.dev/record: df9936-tools/results/6ea553df-5db9-405e-bf01-255b83e52eb9/records/6ea553df-5db9-405e-bf01-255b83e52eb9
    results.tekton.dev/result: df9936-tools/results/6ea553df-5db9-405e-bf01-255b83e52eb9
    results.tekton.dev/stored: 'true'
  resourceVersion: '15071174492'
  name: bcstats-box-pipe-x8ae8w
  uid: 6ea553df-5db9-405e-bf01-255b83e52eb9
  creationTimestamp: '2023-10-17T17:08:47Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pipeline.openshift.io/started-by': {}
          'f:labels':
            .: {}
            'f:tekton.dev/pipeline': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:pipelineRef':
            .: {}
            'f:name': {}
          'f:resources': {}
          'f:status': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-10-17T17:08:47Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:childReferences': {}
          'f:completionTime': {}
          'f:conditions': {}
          'f:pipelineSpec':
            .: {}
            'f:params': {}
            'f:tasks': {}
            'f:workspaces': {}
          'f:skippedTasks': {}
          'f:startTime': {}
      manager: openshift-pipelines-controller
      operation: Update
      subresource: status
      time: '2023-10-17T17:20:36Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:results.tekton.dev/record': {}
            'f:results.tekton.dev/result': {}
            'f:results.tekton.dev/stored': {}
          'f:finalizers':
            .: {}
            'v:"results.tekton.dev/pipelinerun"': {}
      manager: openshift-pipelines-results-watcher
      operation: Update
      time: '2025-07-08T18:02:45Z'
  namespace: df9936-tools
  finalizers:
    - results.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: bcstats-box-pipe
spec:
  params:
    - name: deployenv
      value: dev
    - name: imagetag
      value: upload-fail1
    - name: dobuild
      value: 'yes'
    - name: github-repo-revision
      value: master
  pipelineRef:
    name: bcstats-box-pipe
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
status:
  childReferences:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: bcstats-box-pipe-x8ae8w-git-clone
      pipelineTaskName: git-clone
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: bcstats-box-pipe-x8ae8w-buildah
      pipelineTaskName: buildah
      whenExpressions:
        - input: 'yes'
          operator: in
          values:
            - 'yes'
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: bcstats-box-pipe-x8ae8w-helm-upgrade-from-source
      pipelineTaskName: helm-upgrade-from-source
      whenExpressions:
        - input: dev
          operator: in
          values:
            - dev
            - test
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: bcstats-box-pipe-x8ae8w-helm-dep-update2
      pipelineTaskName: helm-dep-update2
  completionTime: '2023-10-17T17:20:36Z'
  conditions:
    - lastTransitionTime: '2023-10-17T17:20:36Z'
      message: 'Tasks Completed: 4 (Failed: 0, Cancelled 0), Skipped: 1'
      reason: Completed
      status: 'True'
      type: Succeeded
  pipelineSpec:
    params:
      - default: dev
        description: Deployment Environment
        name: deployenv
        type: string
      - default: latest
        description: Image Tag to deploy
        name: imagetag
        type: string
      - default: 'yes'
        description: Build?
        name: dobuild
        type: string
      - default: master
        description: GitHub Repository Revision (branch)
        name: github-repo-revision
        type: string
    tasks:
      - name: git-clone
        params:
          - name: url
            value: 'https://github.com/bcgov/bcstats-lockbox.git'
          - name: revision
            value: master
          - name: refspec
            value: ''
          - name: submodules
            value: 'true'
          - name: depth
            value: '1'
          - name: sslVerify
            value: 'true'
          - name: crtFileName
            value: ca-bundle.crt
          - name: subdirectory
            value: ''
          - name: sparseCheckoutDirectories
            value: ''
          - name: deleteExisting
            value: 'true'
          - name: httpProxy
            value: ''
          - name: httpsProxy
            value: ''
          - name: noProxy
            value: ''
          - name: verbose
            value: 'true'
          - name: gitInitImage
            value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:429ba9c10dfcff4ee0154ab75f9bd06fd306f019c0ed0b062ba7c03e56e3e33b'
          - name: userHome
            value: /home/git
        taskRef:
          kind: ClusterTask
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
      - name: buildah
        params:
          - name: IMAGE
            value: 'image-registry.openshift-image-registry.svc:5000/df9936-tools/bcbox:upload-fail1'
          - name: BUILDER_IMAGE
            value: 'registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084'
          - name: STORAGE_DRIVER
            value: vfs
          - name: DOCKERFILE
            value: ./Dockerfile
          - name: CONTEXT
            value: .
          - name: TLSVERIFY
            value: 'true'
          - name: FORMAT
            value: oci
          - name: BUILD_EXTRA_ARGS
            value: ''
          - name: PUSH_EXTRA_ARGS
            value: ''
          - name: SKIP_PUSH
            value: 'false'
        runAfter:
          - git-clone
        taskRef:
          kind: ClusterTask
          name: buildah
        when:
          - input: 'yes'
            operator: in
            values:
              - 'yes'
        workspaces:
          - name: source
            workspace: shared-workspace
      - name: helm-upgrade-from-source
        params:
          - name: charts_dir
            value: charts/bcbox
          - name: release_version
            value: ''
          - name: release_name
            value: bcstats-bcbox
          - name: release_namespace
            value: df9936-dev
          - name: overwrite_values
            value: 'image.tag=upload-fail1,image.repository=image-registry.openshift-image-registry.svc:5000/df9936-tools,config.enabled=true,config.releaseScoped=true,config.configMap.FRONTEND_OIDC_AUTHORITY=https://dev.loginproxy.gov.bc.ca/auth/realms/standard,config.configMap.FRONTEND_OIDC_CLIENTID=bc-stats-coms-bc-box-4936,config.configMap.FRONTEND_COMS_APIPATH=https://bcstatscoms-dev.apps.gov.bc.ca/api/v1'
          - name: values_file
            value: values.yaml
          - name: helm_image
            value: 'docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae'
          - name: upgrade_extra_params
            value: ''
        runAfter:
          - helm-dep-update2
        taskRef:
          kind: ClusterTask
          name: helm-upgrade-from-source
        when:
          - input: dev
            operator: in
            values:
              - dev
              - test
        workspaces:
          - name: source
            workspace: shared-workspace
      - name: helm-upgrade-prod-from-source
        params:
          - name: charts_dir
            value: charts/bcbox
          - name: release_version
            value: ''
          - name: release_name
            value: bcstats-bcbox
          - name: release_namespace
            value: df9936-dev
          - name: overwrite_values
            value: 'image.tag=upload-fail1,image.repository=image-registry.openshift-image-registry.svc:5000/df9936-tools,config.enabled=true,config.releaseScoped=true,config.configMap.FRONTEND_OIDC_AUTHORITY=https://loginproxy.gov.bc.ca/auth/realms/standard,config.configMap.FRONTEND_OIDC_CLIENTID=bc-stats-coms-bc-box-4936,config.configMap.FRONTEND_COMS_APIPATH=https://bcstatscoms.apps.gov.bc.ca/api/v1'
          - name: values_file
            value: values.yaml
          - name: helm_image
            value: 'docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae'
          - name: upgrade_extra_params
            value: ''
        runAfter:
          - helm-dep-update2
        taskRef:
          kind: ClusterTask
          name: helm-upgrade-from-source
        when:
          - input: dev
            operator: in
            values:
              - prod
        workspaces:
          - name: source
            workspace: shared-workspace
      - name: helm-dep-update2
        runAfter:
          - buildah
        taskRef:
          kind: Task
          name: helm-dep-update2
        workspaces:
          - name: output
            workspace: shared-workspace
    workspaces:
      - name: shared-workspace
  skippedTasks:
    - name: helm-upgrade-prod-from-source
      reason: When Expressions evaluated to false
      whenExpressions:
        - input: dev
          operator: in
          values:
            - prod
  startTime: '2023-10-17T17:08:47Z'
